version: "3.3"

services:
  flask_app:
    build: .
    container_name: flask_app
    environment:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  scheduler:
    build:
      context: .
    environment:
      - FLASK_ENV=production
    command: python scheduler.py
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  app_network:
